import Sound from 'react-native-sound'

export default audios = [
    {
      title: 'Headshake',
      url: 'headshake.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Crickets',
      url: 'crickets.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_4',
      url: 'russian_4.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'The_Next_Level_Play',
      url: 'the_next_level_play.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'I_Cant_Belieeve_What_',
      url: 'i_cant_belieeve_what_.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chicken',
      url: 'chicken.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Uyuy_Huy_Huy_Huy_Huy',
      url: 'uyuy_huy_huy_huy_huy.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Snore',
      url: 'snore.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_6',
      url: 'russian_6.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Ouch',
      url: 'ouch.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_3',
      url: 'chinese_3.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Pudge',
      url: 'pudge.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_1',
      url: 'chinese_1.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_7',
      url: 'chinese_7.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Wakeup',
      url: 'wakeup.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Oh_My_Lord',
      url: 'oh_my_lord.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_6',
      url: 'chinese_6.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Falling',
      url: 'falling.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Brutal_Savage_Rekt',
      url: 'brutal_savage_rekt.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Yahoo',
      url: 'yahoo.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_4',
      url: 'chinese_4.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_2',
      url: 'chinese_2.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Echo_Slamma_Jamma',
      url: 'echo_slamma_jamma.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Its_A_Disastah',
      url: 'its_a_disastah.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Lakad_Matataaag_Normalin_Normalin',
      url: 'lakad_matataaag_normalin_normalin.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Patience_From_Zhou',
      url: 'patience_from_zhou.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Kiss',
      url: 'kiss.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_8',
      url: 'chinese_8.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Eta_Gg',
      url: 'eta_gg.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Sad_Trombone',
      url: 'sad_trombone.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_5',
      url: 'russian_5.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_1',
      url: 'russian_1.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Crybaby',
      url: 'crybaby.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_2',
      url: 'russian_2.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Thats_Pay_To_Win_Baby',
      url: 'thats_pay_to_win_baby.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Theyre_All_Dead',
      url: 'theyre_all_dead.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Claps',
      url: 'claps.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Icefrog',
      url: 'icefrog.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_9',
      url: 'chinese_9.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'I_Uh_That Was Questionab_',
      url: 'I_uh_That was questionab_.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Phantom',
      url: 'phantom.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Youre_A_Goddamn_Hero',
      url: 'youre_a_goddamn_hero.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Krazatie',
      url: 'krazatie.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Dota_Click',
      url: 'dota_click.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_7',
      url: 'russian_7.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Party_Horn',
      url: 'party_horn.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_8',
      url: 'russian_8.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Easiest_Money_Of_My_Life',
      url: 'easiest_money_of_my_life.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Eta Prosta Niesta',
      url: 'eta prosta niesta.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Magicfunction.Py',
      url: 'magicfunction.py',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Drum_Roll',
      url: 'drum_roll.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Drum',
      url: 'drum.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Russian_3',
      url: 'russian_3.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Chinese_5',
      url: 'chinese_5.mp3',
      basePath: Sound.MAIN_BUNDLE
    }, {
      title: 'Waow',
      url: 'waow.mp3',
      basePath: Sound.MAIN_BUNDLE
    }
  ]
